export const products = [
  {
    id: 1,
    product_name: 'Product-7637',
    category: 'Electronics',
    brand: 'BrandC',
    description: 'New arrival.',
    price: 940.64,
  },
  {
    id: 2,
    product_name: 'Product-2158',
    category: 'Home Appliances',
    brand: 'BrandE',
    description: 'Highly recommended.',
    price: 832.1,
  },
  {
    id: 3,
    product_name: 'Product-9897',
    category: 'Home Appliances',
    brand: 'BrandD',
    description: 'Limited edition.',
    price: 253.32,
  },
  {
    id: 4,
    product_name: 'Product-3315',
    category: 'Toys',
    brand: 'BrandD',
    description: 'Highly recommended.',
    price: 164.84,
  },
  {
    id: 5,
    product_name: 'Product-5042',
    category: 'Books',
    brand: 'BrandC',
    description: 'Best seller.',
    price: 484.81,
  },
  {
    id: 6,
    product_name: 'Product-9964',
    category: 'Home Appliances',
    brand: 'BrandA',
    description: 'High quality product.',
    price: 500.53,
  },
  {
    id: 7,
    product_name: 'Product-5441',
    category: 'Books',
    brand: 'BrandD',
    description: 'High quality product.',
    price: 997.49,
  },
  {
    id: 8,
    product_name: 'Product-8327',
    category: 'Home Appliances',
    brand: 'BrandA',
    description: 'New arrival.',
    price: 370.6,
  },
  {
    id: 9,
    product_name: 'Product-7418',
    category: 'Electronics',
    brand: 'BrandB',
    description: 'New arrival.',
    price: 323.65,
  },
  {
    id: 10,
    product_name: 'Product-1017',
    category: 'Toys',
    brand: 'BrandE',
    description: 'High quality product.',
    price: 627.41,
  },
  {
    id: 11,
    product_name: 'Product-4538',
    category: 'Home Appliances',
    brand: 'BrandB',
    description: 'Limited edition.',
    price: 598.65,
  },
  {
    id: 12,
    product_name: 'Product-4490',
    category: 'Fashion',
    brand: 'BrandB',
    description: 'New arrival.',
    price: 704.11,
  },
  {
    id: 13,
    product_name: 'Product-9486',
    category: 'Fashion',
    brand: 'BrandA',
    description: 'New arrival.',
    price: 764.2,
  },
  {
    id: 14,
    product_name: 'Product-5788',
    category: 'Toys',
    brand: 'BrandB',
    description: 'New arrival.',
    price: 526.63,
  },
  {
    id: 15,
    product_name: 'Product-7671',
    category: 'Toys',
    brand: 'BrandC',
    description: 'Highly recommended.',
    price: 597.35,
  },
  {
    id: 16,
    product_name: 'Product-5735',
    category: 'Fashion',
    brand: 'BrandD',
    description: 'High quality product.',
    price: 740.85,
  },
  {
    id: 17,
    product_name: 'Product-5473',
    category: 'Toys',
    brand: 'BrandD',
    description: 'Highly recommended.',
    price: 219.49,
  },
  {
    id: 18,
    product_name: 'Product-2251',
    category: 'Books',
    brand: 'BrandA',
    description: 'New arrival.',
    price: 509.32,
  },
  {
    id: 19,
    product_name: 'Product-6443',
    category: 'Home Appliances',
    brand: 'BrandD',
    description: 'Affordable price.',
    price: 165.43,
  },
  {
    id: 20,
    product_name: 'Product-2891',
    category: 'Electronics',
    brand: 'BrandE',
    description: 'Highly recommended.',
    price: 831.98,
  },
  {
    id: 21,
    product_name: 'Product-3258',
    category: 'Books',
    brand: 'BrandA',
    description: 'New arrival.',
    price: 851.99,
  },
  {
    id: 22,
    product_name: 'Product-1220',
    category: 'Fashion',
    brand: 'BrandC',
    description: 'Best seller.',
    price: 133.04,
  },
  {
    id: 23,
    product_name: 'Product-2872',
    category: 'Home Appliances',
    brand: 'BrandC',
    description: 'Affordable price.',
    price: 675.96,
  },
  {
    id: 24,
    product_name: 'Product-4298',
    category: 'Toys',
    brand: 'BrandC',
    description: 'Best seller.',
    price: 725.08,
  },
  {
    id: 25,
    product_name: 'Product-2020',
    category: 'Books',
    brand: 'BrandE',
    description: 'Limited edition.',
    price: 18.63,
  },
  {
    id: 26,
    product_name: 'Product-5414',
    category: 'Electronics',
    brand: 'BrandC',
    description: 'High quality product.',
    price: 81.23,
  },
  {
    id: 27,
    product_name: 'Product-9593',
    category: 'Electronics',
    brand: 'BrandA',
    description: 'Highly recommended.',
    price: 745.7,
  },
  {
    id: 28,
    product_name: 'Product-6145',
    category: 'Home Appliances',
    brand: 'BrandC',
    description: 'Limited edition.',
    price: 526.88,
  },
  {
    id: 29,
    product_name: 'Product-7081',
    category: 'Books',
    brand: 'BrandC',
    description: 'Best seller.',
    price: 802.49,
  },
  {
    id: 30,
    product_name: 'Product-6051',
    category: 'Toys',
    brand: 'BrandE',
    description: 'Highly recommended.',
    price: 913.93,
  },
  {
    id: 31,
    product_name: 'Product-8474',
    category: 'Books',
    brand: 'BrandE',
    description: 'New arrival.',
    price: 620.57,
  },
  {
    id: 32,
    product_name: 'Product-8613',
    category: 'Books',
    brand: 'BrandC',
    description: 'Affordable price.',
    price: 126.54,
  },
  {
    id: 33,
    product_name: 'Product-9518',
    category: 'Books',
    brand: 'BrandD',
    description: 'Affordable price.',
    price: 757.65,
  },
  {
    id: 34,
    product_name: 'Product-6472',
    category: 'Fashion',
    brand: 'BrandB',
    description: 'Limited edition.',
    price: 774.95,
  },
  {
    id: 35,
    product_name: 'Product-6056',
    category: 'Fashion',
    brand: 'BrandB',
    description: 'Affordable price.',
    price: 348.89,
  },
  {
    id: 36,
    product_name: 'Product-3822',
    category: 'Home Appliances',
    brand: 'BrandA',
    description: 'Limited edition.',
    price: 852.42,
  },
  {
    id: 37,
    product_name: 'Product-2656',
    category: 'Books',
    brand: 'BrandD',
    description: 'Limited edition.',
    price: 679.33,
  },
  {
    id: 38,
    product_name: 'Product-7318',
    category: 'Toys',
    brand: 'BrandE',
    description: 'Limited edition.',
    price: 902.32,
  },
  {
    id: 39,
    product_name: 'Product-5099',
    category: 'Home Appliances',
    brand: 'BrandA',
    description: 'Highly recommended.',
    price: 478.25,
  },
  {
    id: 40,
    product_name: 'Product-2218',
    category: 'Toys',
    brand: 'BrandA',
    description: 'Limited edition.',
    price: 728.58,
  },
  {
    id: 41,
    product_name: 'Product-1591',
    category: 'Home Appliances',
    brand: 'BrandB',
    description: 'Best seller.',
    price: 819.67,
  },
  {
    id: 42,
    product_name: 'Product-8526',
    category: 'Books',
    brand: 'BrandD',
    description: 'High quality product.',
    price: 785.81,
  },
  {
    id: 43,
    product_name: 'Product-7042',
    category: 'Books',
    brand: 'BrandA',
    description: 'Limited edition.',
    price: 31.93,
  },
  {
    id: 44,
    product_name: 'Product-1172',
    category: 'Home Appliances',
    brand: 'BrandA',
    description: 'High quality product.',
    price: 584.67,
  },
  {
    id: 45,
    product_name: 'Product-1340',
    category: 'Home Appliances',
    brand: 'BrandB',
    description: 'Highly recommended.',
    price: 45.64,
  },
  {
    id: 46,
    product_name: 'Product-8418',
    category: 'Home Appliances',
    brand: 'BrandA',
    description: 'Best seller.',
    price: 765.69,
  },
  {
    id: 47,
    product_name: 'Product-5004',
    category: 'Toys',
    brand: 'BrandA',
    description: 'Affordable price.',
    price: 556.83,
  },
  {
    id: 48,
    product_name: 'Product-2586',
    category: 'Electronics',
    brand: 'BrandB',
    description: 'Best seller.',
    price: 53.74,
  },
  {
    id: 49,
    product_name: 'Product-3494',
    category: 'Fashion',
    brand: 'BrandE',
    description: 'Highly recommended.',
    price: 681.27,
  },
  {
    id: 50,
    product_name: 'Product-3950',
    category: 'Electronics',
    brand: 'BrandB',
    description: 'Best seller.',
    price: 648.7,
  },
  {
    id: 51,
    product_name: 'Product-2585',
    category: 'Fashion',
    brand: 'BrandD',
    description: 'Best seller.',
    price: 450.83,
  },
  {
    id: 52,
    product_name: 'Product-7850',
    category: 'Electronics',
    brand: 'BrandA',
    description: 'High quality product.',
    price: 312.71,
  },
  {
    id: 53,
    product_name: 'Product-8910',
    category: 'Home Appliances',
    brand: 'BrandE',
    description: 'Best seller.',
    price: 77.61,
  },
  {
    id: 54,
    product_name: 'Product-5929',
    category: 'Home Appliances',
    brand: 'BrandE',
    description: 'Limited edition.',
    price: 386.4,
  },
  {
    id: 55,
    product_name: 'Product-6675',
    category: 'Home Appliances',
    brand: 'BrandE',
    description: 'Limited edition.',
    price: 18.52,
  },
  {
    id: 56,
    product_name: 'Product-2296',
    category: 'Toys',
    brand: 'BrandE',
    description: 'Affordable price.',
    price: 127.11,
  },
  {
    id: 57,
    product_name: 'Product-2040',
    category: 'Electronics',
    brand: 'BrandC',
    description: 'Best seller.',
    price: 348.75,
  },
  {
    id: 58,
    product_name: 'Product-5385',
    category: 'Toys',
    brand: 'BrandA',
    description: 'Best seller.',
    price: 956.47,
  },
  {
    id: 59,
    product_name: 'Product-9600',
    category: 'Electronics',
    brand: 'BrandD',
    description: 'Highly recommended.',
    price: 399.95,
  },
  {
    id: 60,
    product_name: 'Product-8484',
    category: 'Home Appliances',
    brand: 'BrandB',
    description: 'New arrival.',
    price: 721.89,
  },
  {
    id: 61,
    product_name: 'Product-4970',
    category: 'Home Appliances',
    brand: 'BrandE',
    description: 'New arrival.',
    price: 24.61,
  },
  {
    id: 62,
    product_name: 'Product-4828',
    category: 'Fashion',
    brand: 'BrandB',
    description: 'New arrival.',
    price: 496.07,
  },
  {
    id: 63,
    product_name: 'Product-6029',
    category: 'Electronics',
    brand: 'BrandD',
    description: 'High quality product.',
    price: 969.74,
  },
  {
    id: 64,
    product_name: 'Product-6209',
    category: 'Electronics',
    brand: 'BrandE',
    description: 'Affordable price.',
    price: 810.33,
  },
  {
    id: 65,
    product_name: 'Product-8951',
    category: 'Electronics',
    brand: 'BrandE',
    description: 'High quality product.',
    price: 969.81,
  },
  {
    id: 66,
    product_name: 'Product-4204',
    category: 'Books',
    brand: 'BrandC',
    description: 'New arrival.',
    price: 595.11,
  },
  {
    id: 67,
    product_name: 'Product-7295',
    category: 'Home Appliances',
    brand: 'BrandB',
    description: 'High quality product.',
    price: 24.44,
  },
  {
    id: 68,
    product_name: 'Product-8764',
    category: 'Toys',
    brand: 'BrandD',
    description: 'New arrival.',
    price: 538.55,
  },
  {
    id: 69,
    product_name: 'Product-4275',
    category: 'Home Appliances',
    brand: 'BrandE',
    description: 'High quality product.',
    price: 416.09,
  },
  {
    id: 70,
    product_name: 'Product-4938',
    category: 'Books',
    brand: 'BrandC',
    description: 'Affordable price.',
    price: 104.25,
  },
  {
    id: 71,
    product_name: 'Product-2273',
    category: 'Toys',
    brand: 'BrandC',
    description: 'Highly recommended.',
    price: 97.96,
  },
  {
    id: 72,
    product_name: 'Product-3712',
    category: 'Home Appliances',
    brand: 'BrandA',
    description: 'Best seller.',
    price: 343.89,
  },
  {
    id: 73,
    product_name: 'Product-3010',
    category: 'Books',
    brand: 'BrandA',
    description: 'Best seller.',
    price: 486.36,
  },
  {
    id: 74,
    product_name: 'Product-8310',
    category: 'Home Appliances',
    brand: 'BrandB',
    description: 'New arrival.',
    price: 765.78,
  },
  {
    id: 75,
    product_name: 'Product-4148',
    category: 'Toys',
    brand: 'BrandB',
    description: 'Limited edition.',
    price: 365.22,
  },
  {
    id: 76,
    product_name: 'Product-7649',
    category: 'Toys',
    brand: 'BrandC',
    description: 'Best seller.',
    price: 132.75,
  },
  {
    id: 77,
    product_name: 'Product-1412',
    category: 'Toys',
    brand: 'BrandB',
    description: 'Affordable price.',
    price: 265.67,
  },
  {
    id: 78,
    product_name: 'Product-8293',
    category: 'Fashion',
    brand: 'BrandD',
    description: 'New arrival.',
    price: 417.19,
  },
  {
    id: 79,
    product_name: 'Product-6778',
    category: 'Electronics',
    brand: 'BrandC',
    description: 'Highly recommended.',
    price: 267.49,
  },
  {
    id: 80,
    product_name: 'Product-3048',
    category: 'Electronics',
    brand: 'BrandE',
    description: 'Affordable price.',
    price: 557.32,
  },
  {
    id: 81,
    product_name: 'Product-1350',
    category: 'Home Appliances',
    brand: 'BrandB',
    description: 'Highly recommended.',
    price: 708.97,
  },
  {
    id: 82,
    product_name: 'Product-9115',
    category: 'Fashion',
    brand: 'BrandD',
    description: 'High quality product.',
    price: 925.61,
  },
  {
    id: 83,
    product_name: 'Product-6253',
    category: 'Toys',
    brand: 'BrandA',
    description: 'High quality product.',
    price: 423.37,
  },
  {
    id: 84,
    product_name: 'Product-9553',
    category: 'Electronics',
    brand: 'BrandE',
    description: 'High quality product.',
    price: 353.66,
  },
  {
    id: 85,
    product_name: 'Product-6345',
    category: 'Fashion',
    brand: 'BrandA',
    description: 'Best seller.',
    price: 43.51,
  },
  {
    id: 86,
    product_name: 'Product-8435',
    category: 'Home Appliances',
    brand: 'BrandB',
    description: 'High quality product.',
    price: 410.14,
  },
  {
    id: 87,
    product_name: 'Product-9025',
    category: 'Home Appliances',
    brand: 'BrandC',
    description: 'High quality product.',
    price: 840.87,
  },
  {
    id: 88,
    product_name: 'Product-2998',
    category: 'Home Appliances',
    brand: 'BrandC',
    description: 'Highly recommended.',
    price: 483.12,
  },
  {
    id: 89,
    product_name: 'Product-9830',
    category: 'Books',
    brand: 'BrandE',
    description: 'Limited edition.',
    price: 818.03,
  },
  {
    id: 90,
    product_name: 'Product-8980',
    category: 'Electronics',
    brand: 'BrandA',
    description: 'Best seller.',
    price: 214.25,
  },
  {
    id: 91,
    product_name: 'Product-7455',
    category: 'Fashion',
    brand: 'BrandC',
    description: 'Affordable price.',
    price: 461.79,
  },
  {
    id: 92,
    product_name: 'Product-1912',
    category: 'Toys',
    brand: 'BrandE',
    description: 'Limited edition.',
    price: 807.97,
  },
  {
    id: 93,
    product_name: 'Product-9343',
    category: 'Books',
    brand: 'BrandD',
    description: 'Best seller.',
    price: 992.69,
  },
  {
    id: 94,
    product_name: 'Product-2694',
    category: 'Home Appliances',
    brand: 'BrandB',
    description: 'Best seller.',
    price: 579.71,
  },
  {
    id: 95,
    product_name: 'Product-5380',
    category: 'Toys',
    brand: 'BrandC',
    description: 'New arrival.',
    price: 704.48,
  },
  {
    id: 96,
    product_name: 'Product-8869',
    category: 'Fashion',
    brand: 'BrandC',
    description: 'Highly recommended.',
    price: 825.28,
  },
  {
    id: 97,
    product_name: 'Product-3565',
    category: 'Home Appliances',
    brand: 'BrandB',
    description: 'Highly recommended.',
    price: 40.22,
  },
  {
    id: 98,
    product_name: 'Product-5098',
    category: 'Electronics',
    brand: 'BrandE',
    description: 'Affordable price.',
    price: 408.98,
  },
  {
    id: 99,
    product_name: 'Product-4982',
    category: 'Electronics',
    brand: 'BrandE',
    description: 'Limited edition.',
    price: 312.41,
  },
  {
    id: 100,
    product_name: 'Product-6707',
    category: 'Fashion',
    brand: 'BrandD',
    description: 'Limited edition.',
    price: 272.45,
  },
];
